<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Outlet;
use App\Models\Distributor;
use App\Models\City;

class OutletSeeder extends Seeder
{
    public function run(): void
    {
        $outletsData = [
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "AJM Petshop",
                'nama_pic' => 'PIC ' . "AJM Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Gangsalan, Kalitidu, Kec. Kalitidu, Kabupaten Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://maps.app.goo.gl/Je7t7BzTeiarg2Eo6",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Aulia Petshop & Praktek Dokter Hewan",
                'nama_pic' => 'PIC ' . "Aulia Petshop & Praktek Dokter Hewan",
                'whatsapp' => "082132395055",
                'alamat_lengkap' => "Jl. Ahmad yani no. 2A, jambean sukorejo kec. Bojonegoro kab. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/EZVaLQaCY9CMYuvU8",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Aulia Petshop Baureno",
                'nama_pic' => 'PIC ' . "Aulia Petshop Baureno",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl raya baureno no. 98, pasinan kec. Baureno kab. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/B6V8qbLkJ1jnTdqo9",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Aulia Petshop Padangan",
                'nama_pic' => 'PIC ' . "Aulia Petshop Padangan",
                'whatsapp' => "082144721568",
                'alamat_lengkap' => "Ruko jl. Surabaya no.9 dusun demaan, dengok, padangan, bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/MssCwfauBcsRJwm66",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Ilhampuss22 Petshop",
                'nama_pic' => 'PIC ' . "Ilhampuss22 Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Cepit, Sumuragung, Kec. Sumberejo, Kabupaten Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://maps.app.goo.gl/8jzyi5j261juGRhM8",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Puffy Petshop",
                'nama_pic' => 'PIC ' . "Puffy Petshop",
                'whatsapp' => "085338601567",
                'alamat_lengkap' => "Gg. Nanas 1, Kabunan Lor, Kabunan, Kec. Balen, Kabupaten Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://maps.app.goo.gl/LR9kKtYr9QAqc1bj6",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Yavet Animal Care",
                'nama_pic' => 'PIC ' . "Yavet Animal Care",
                'whatsapp' => "085230329980",
                'alamat_lengkap' => "Jl. Desa Purwoasri Sukosewu, Klapak, Sitiaji, Kec.Sukosewu, kab.bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/vWwTKnkNMqt89hxM8",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Rizky Petshop",
                'nama_pic' => 'PIC ' . "Rizky Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Dander, Dander, Kec. Dander, Kab Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/STjDKedVMhRxvppt7",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Firdaus Pet Care",
                'nama_pic' => 'PIC ' . "Firdaus Pet Care",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Gondang No 6, Tikung Wetan, Gondang, Kec. Gondang, Kab. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/QoDjyy4zh42Qjnyc7",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Batu",
                'nama_outlet' => "Ndek Kene",
                'nama_pic' => 'PIC ' . "Ndek Kene",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Brigjen Abdul Manan Wijaya RT03 Pujon Lor (Barat Bank Jatim)",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Ndek+Kene+Pujon+Lor",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Batu",
                'nama_outlet' => "D'Clinic",
                'nama_pic' => 'PIC ' . "D'Clinic",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Semeru No 18, Sisir, Batu",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=D'Clinic+Jl+Semeru+No+18+Batu",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Malang",
                'nama_outlet' => "Planet Petcare Karangploso",
                'nama_pic' => 'PIC ' . "Planet Petcare Karangploso",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Ruko Raya Griya Permata Alakm Kav 12 Ngijo - Karangploso Kab. Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Planet+Petcare+Karangploso",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Malang",
                'nama_outlet' => "Planet Pet Care Tirto Joyo",
                'nama_pic' => 'PIC ' . "Planet Pet Care Tirto Joyo",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Tirto Joyo Blok DD No. 134 Merjosari, Kota Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Planet+Pet+Care+Tirto+Joyo+Merjosari",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Batu",
                'nama_outlet' => "Tera PetShop",
                'nama_pic' => 'PIC ' . "Tera PetShop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Patimura No.41, Temas, Kec. Batu, Kota Batu",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Tera+PetShop+Batu",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Malang",
                'nama_outlet' => "Nanang Petshop",
                'nama_pic' => 'PIC ' . "Nanang Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Tasikmadu No.21, Karangploso Wetan, Kepuharjo, Kec. Lowokwaru, Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Nanang+Petshop+Malang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Malang",
                'nama_outlet' => "Mendit Petshop",
                'nama_pic' => 'PIC ' . "Mendit Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Wendit Tim. No.36, Mangliawan, Kec. Pakis, Kab. Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Mendit+Petshop+Malang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Malang",
                'nama_outlet' => "Toko Ardi",
                'nama_pic' => 'PIC ' . "Toko Ardi",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Brigjend Abd Manan Wijaya, Maron, Pujon Lor, Kec. Pujon, Kab. Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Toko+Ardi+Pujon+Malang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Sidoarjo",
                'nama_outlet' => "MOMO PETTO PETSHOP",
                'nama_pic' => 'PIC ' . "MOMO PETTO PETSHOP",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Ruko Graha Tirta, Jl. Tirta Raya No 5, Waru, Sidoarjo",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=MOMO+PETTO+PETSHOP+Sidoarjo",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Pati",
                'nama_outlet' => "Aqila Petshop",
                'nama_pic' => 'PIC ' . "Aqila Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jalan Pati-Tayu KM. 10 Pati, Jawa Tengah",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Aqila+Petshop+Pati+Tayu",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Surakarta",
                'nama_outlet' => "Dunia Pet Nusukan",
                'nama_pic' => 'PIC ' . "Dunia Pet Nusukan",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl Kpt. Pierre Tendean no 14 Nusukan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Dunia+Pet+Nusukan",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Surakarta",
                'nama_outlet' => "Dunia Pet Fajar Indah",
                'nama_pic' => 'PIC ' . "Dunia Pet Fajar Indah",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Ruko fajar indah raya 2 Jl. Fajar indah raya Klemburan - baturan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Dunia+Pet+Fajar+Indah",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Sukoharjo",
                'nama_outlet' => "Dunia Pet Gentan",
                'nama_pic' => 'PIC ' . "Dunia Pet Gentan",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Joko Tingkir no 17 Makamhaji - Kartosuro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Dunia+Pet+Gentan",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Karanganyar",
                'nama_outlet' => "Dodi Petshop Jaten",
                'nama_pic' => 'PIC ' . "Dodi Petshop Jaten",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Solo - Tawangmangu (Depan Ary Farma Jaten)",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Dodi+Petshop+Jaten",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Surakarta",
                'nama_outlet' => "Kawatan Petshop & Klinik",
                'nama_pic' => 'PIC ' . "Kawatan Petshop & Klinik",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Muh Yamin 95 Kratonan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Kawatan+Petshop+Solo",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Sukoharjo",
                'nama_outlet' => "Happypets Petshop & Klinik",
                'nama_pic' => 'PIC ' . "Happypets Petshop & Klinik",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Grogol 74 Grogol - Sukoharjo",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Happypets+Petshop+Grogol",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Sukoharjo",
                'nama_outlet' => "R2 Petshop",
                'nama_pic' => 'PIC ' . "R2 Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Tawangsari - Sukoharjo",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=R2+Petshop+Tawangsari",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Surakarta",
                'nama_outlet' => "Herstel Sozo Petshop & Klinik",
                'nama_pic' => 'PIC ' . "Herstel Sozo Petshop & Klinik",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Aru no 28A Pantisari - Kepatihan, Jebres, Solo",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Herstel+Sozo+Petshop+Solo",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Surakarta",
                'nama_outlet' => "Nemo Petshop",
                'nama_pic' => 'PIC ' . "Nemo Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. RM Said no 127 Punggawan - Solo",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Nemo+Petshop+Solo",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Karanganyar",
                'nama_outlet' => "Yuca Petshop",
                'nama_pic' => 'PIC ' . "Yuca Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Nusama, Dalon, Ngringo",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Yuca+Petshop+Ngringo",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Gukgukmeong",
                'nama_pic' => 'PIC ' . "Gukgukmeong",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Kampung Baris 505, Karangturi, Kec. Semarang Timur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Gukgukmeong+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Arga Petshop",
                'nama_pic' => 'PIC ' . "Arga Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Komplek Ruko ANDA, Jl. Tlaga Asmara no.1b",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Arga+Petshop+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Kharisma Petshop",
                'nama_pic' => 'PIC ' . "Kharisma Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Parang Baris Raya 14, Tlogosari Kulon, Kec. Pedurungan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Kharisma+Petshop+Tlogosari+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Kharisma Petshop Pasbur",
                'nama_pic' => 'PIC ' . "Kharisma Petshop Pasbur",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Purwosari Raya, Rejosari, Semarang Timur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Kharisma+Petshop+Cabang+Pasar+Burung",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Bingo Petshop",
                'nama_pic' => 'PIC ' . "Bingo Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Ngaliyan Raya No.10a, Purwoyoso, Kec. Ngaliyan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Bingo+Petshop+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Mocca Shop",
                'nama_pic' => 'PIC ' . "Mocca Shop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "JI. Parang Kembang X no. 22, Tlogosari, Semarang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Mocca+Shop+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Mochi Petshop",
                'nama_pic' => 'PIC ' . "Mochi Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Menoreh Raya No.5, Sampangan, Kec. Gajahmungkur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Mochi+Petshop+Sampangan",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Mochi 2 Petshop",
                'nama_pic' => 'PIC ' . "Mochi 2 Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Karangrejo No. 50, Srondol Wetan - Banyumanik",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Mochi+2+Petshop+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Jolie Petshop",
                'nama_pic' => 'PIC ' . "Jolie Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Suyudono No.164, Bulustalan, Kec. Semarang Selatan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Jolie+Petshop+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Deva Petshop",
                'nama_pic' => 'PIC ' . "Deva Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Jayengan No. 6, Barusari, Semarang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Deva+Petshop+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "Boss MOP",
                'nama_pic' => 'PIC ' . "Boss MOP",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Malangsari V No. 6, Tlogosari Kulon, Semarang Timur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Boss+MOP+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Semarang",
                'nama_outlet' => "TBS Merakyat",
                'nama_pic' => 'PIC ' . "TBS Merakyat",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Brotojoyo Timur III No. 7, Semarang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=TBS+Merakyat+Semarang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cilacap",
                'nama_outlet' => "Petshop Kroya",
                'nama_pic' => 'PIC ' . "Petshop Kroya",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Dongkelan, Kroya, Kec. Kroya",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Petshop+Kroya",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cilacap",
                'nama_outlet' => "Petshop Handi",
                'nama_pic' => 'PIC ' . "Petshop Handi",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Sindoro Rt 4/8 Desa Patimuan, Kelurahan Patimuan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Petshop+Handi+Patimuan",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cilacap",
                'nama_outlet' => "Petshop Cherry",
                'nama_pic' => 'PIC ' . "Petshop Cherry",
                'whatsapp' => "081393191233",
                'alamat_lengkap' => "Jl. Mangga No. 27 Rt 01 Rw 07 Desa Adipala, Kec. Adipala",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Petshop+Cherry+Adipala",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cirebon",
                'nama_outlet' => "Bima Petshop",
                'nama_pic' => 'PIC ' . "Bima Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Yudhasari II, Sunyaragi, Kec. Kesambi, Kota Cirebon",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Bima+Petshop+Cirebon",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cirebon",
                'nama_outlet' => "Detail Petshop",
                'nama_pic' => 'PIC ' . "Detail Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. DR. Cipto Mangunkusumo No.191, Pekiringan, Kesambi, Cirebon",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Detail+Petshop+Cirebon",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cirebon",
                'nama_outlet' => "HK Petshop",
                'nama_pic' => 'PIC ' . "HK Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Kebarepan, Kec. Plumbon, Cirebon",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=HK+Petshop+Cirebon",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Cirebon",
                'nama_outlet' => "Griya Sato Petshop",
                'nama_pic' => 'PIC ' . "Griya Sato Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Sumber-Cirebon, Sendang, Kec. Sumber, Cirebon",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Griya+Sato+Petshop+Cirebon",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Lefa Petshop",
                'nama_pic' => 'PIC ' . "Lefa Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Padang - Bengkulu, Bungus Sel., Kec. Bungus Tlk. Kabung",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Lefa+Petshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Labersa Poultry & Petshop",
                'nama_pic' => 'PIC ' . "Labersa Poultry & Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Korong Gadang, Kec. Kuranji, Kota Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Labersa+petshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Hiro Cat Shop",
                'nama_pic' => 'PIC ' . "Hiro Cat Shop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Pagambiran Ampalu Nan XX, Kec. Lubuk Begalung, Kota Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Hiro+Cat+Shop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Talago Petshop Balai Baru",
                'nama_pic' => 'PIC ' . "Talago Petshop Balai Baru",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Balai Baru No.16, Sungai Sapih, Kuranji, Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Talago+Petshop+Balai+Baru",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Talago Petshop Lubuk Minturun",
                'nama_pic' => 'PIC ' . "Talago Petshop Lubuk Minturun",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Lubuk Minturun No.8, Koto Panjang Ikua Koto, Koto Tangah",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Talago+Petshop+Lubuk+Minturun",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Danbo Catshop",
                'nama_pic' => 'PIC ' . "Danbo Catshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Siteba No.34, Surau Gadang, Nanggalo, Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Danbo+Catshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Gatri Vet & Petshop",
                'nama_pic' => 'PIC ' . "Gatri Vet & Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Bypass km 10, Pilakuik, Gn. Sarik, Kec. Kuranji, Kota Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Gatri+Vet+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Yunna Petshop",
                'nama_pic' => 'PIC ' . "Yunna Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Jeruk Raya No.27, Kuranji, Kec. Kuranji, Kota Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Yunna+Petshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Milenia Petshop",
                'nama_pic' => 'PIC ' . "Milenia Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Gunung Pangilun, Padang Utara, Kota Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Milenia+Petshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Davi Catshop",
                'nama_pic' => 'PIC ' . "Davi Catshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Gajah Mada Dalam No.14, Kp. Olo, Kec. Nanggalo, Kota Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Davi+catshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Firyanda Petshop",
                'nama_pic' => 'PIC ' . "Firyanda Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "JI. Kurao Pagan, Kec. Nanggalo, Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Firyanda+Petshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Padang",
                'nama_outlet' => "Cipta Petshop",
                'nama_pic' => 'PIC ' . "Cipta Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "JI. Sutan Syahrir No 33, Sebrang Padang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Cipta+Petshop+Padang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bekasi",
                'nama_outlet' => "Transpet Jakarta",
                'nama_pic' => 'PIC ' . "Transpet Jakarta",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Swatantra No.168, Jatirasa, Kec. Jatiasih, Kota Bekasi",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Transpet+Jakarta",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Bogor",
                'nama_outlet' => "Rovver Paw Petshop Cileungsi",
                'nama_pic' => 'PIC ' . "Rovver Paw Petshop Cileungsi",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Metland Transyogi, Cileungsi Kidul, Kec. Cileungsi, Bogor",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Rovver+Paw+Petshop+Cileungsi",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Depok",
                'nama_outlet' => "AGJ Petshop",
                'nama_pic' => 'PIC ' . "AGJ Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Akses UI No.50, Tugu, Kec. Cimanggis, Kota Depok",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=AGJ+Petshop+Depok",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Depok",
                'nama_outlet' => "Bon Bon Pet Supplies",
                'nama_pic' => 'PIC ' . "Bon Bon Pet Supplies",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Pasir Putih No.2A, Sawangan, Depok",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Bon+Bon+Pet+Supplies+Depok",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Depok",
                'nama_outlet' => "RG.Vet Petshop",
                'nama_pic' => 'PIC ' . "RG.Vet Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Citayam No.15, Pd. Jaya, Kec. Cipayung, Depok",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=RG+Vet+Petshop+Depok",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Jakarta Timur",
                'nama_outlet' => "CV Pet Nusa Bersaudara",
                'nama_pic' => 'PIC ' . "CV Pet Nusa Bersaudara",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Pertengahan No.14, Cijantung, Ps. Rebo, Jakarta Timur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=CV+Pet+Nusa+Bersaudara",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Jakarta Timur",
                'nama_outlet' => "Ovi Petshop",
                'nama_pic' => 'PIC ' . "Ovi Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Pucung 3 No.8, Balekambang, Kramat Jati, Jakarta Timur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Ovi+Petshop+Jakarta",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Tangerang",
                'nama_outlet' => "Negeri Fauna Petshop",
                'nama_pic' => 'PIC ' . "Negeri Fauna Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Regency Blok D5 No.53, Gembor, Kota Tangerang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://www.google.com/maps/search/?api=1&query=Negeri+Fauna+Petshop+Tangerang",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Gresik",
                'nama_outlet' => "Kitty Catshop",
                'nama_pic' => 'PIC ' . "Kitty Catshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Tegal Sari, Dusun Buncitan, Sidomukti, Kec. Bungah, Kabupaten Gresik",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://maps.app.goo.gl/dyacuDLv1bcW2Eqn6",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Tuban",
                'nama_outlet' => "Dewi Cat House",
                'nama_pic' => 'PIC ' . "Dewi Cat House",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jln Panglima Sudirman no 190 RT 1 rw 4 Sidomulyo Tuban",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://maps.app.goo.gl/YQGDe2wKdeRcR6hr9",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Tuban",
                'nama_outlet' => "Vivetcare",
                'nama_pic' => 'PIC ' . "Vivetcare",
                'whatsapp' => "081233676727",
                'alamat_lengkap' => "Perumahan Bukit Karang JL. Intan ll, Blok AJ-7, Tuban",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/D1RFXW7VkF6uumYS8",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Tuban",
                'nama_outlet' => "Oke Vetcare",
                'nama_pic' => 'PIC ' . "Oke Vetcare",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Raya Tambakboyo, Sobontoro Kec. Tambakboyo, Tuban",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/WSvMpGdyigkv5M7DA",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Tuban",
                'nama_outlet' => "Bramasco Cat House",
                'nama_pic' => 'PIC ' . "Bramasco Cat House",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Patimura no. 13 (FOTO COPY BRAMASCO) Tuban, Jawa Timur",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://maps.app.goo.gl/mQ1xJ4Bc3CRG8hAN6",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => true,
                'city_name' => "Lamongan",
                'nama_outlet' => "Azria Petshop",
                'nama_pic' => 'PIC ' . "Azria Petshop",
                'whatsapp' => "081234567890",
                'alamat_lengkap' => "Jl. Veteran No 74 Lamongan",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => "https://goo.gl/maps/SuJyGX2tmjnpFCQN6",
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Sugiarto Petshop",
                'nama_pic' => 'PIC ' . "Sugiarto Petshop",
                'whatsapp' => "082153595160",
                'alamat_lengkap' => "Jl. Untung Suropati No.56A, Sumbang, Klangon, Kec. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Sugiarto Petshop Bojonegoro"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Net Petshop Bojonegoro",
                'nama_pic' => 'PIC ' . "Net Petshop Bojonegoro",
                'whatsapp' => "081335754643",
                'alamat_lengkap' => "Jl. Setyobudi No.7C, Klangon, Kec. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Net Petshop Bojonegoro Bojonegoro"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Gubuk Satwa Bojonegoro",
                'nama_pic' => 'PIC ' . "Gubuk Satwa Bojonegoro",
                'whatsapp' => "085236606637",
                'alamat_lengkap' => "Jl. Lettu Suwolo No.99, RT.18/RW.03, Ngrowo, Kec. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Gubuk Satwa Bojonegoro Bojonegoro"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Bojonegoro",
                'nama_outlet' => "Nathan Cat House",
                'nama_pic' => 'PIC ' . "Nathan Cat House",
                'whatsapp' => "082244894199",
                'alamat_lengkap' => "Jl. Panglima Polim (Sebelah ATM BNI), Sumbang, Kec. Bojonegoro",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Nathan Cat House Bojonegoro"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Blitar",
                'nama_outlet' => "Vetma Pet and Poultry Shop",
                'nama_pic' => 'PIC ' . "Vetma Pet and Poultry Shop",
                'whatsapp' => "085695188823",
                'alamat_lengkap' => "Green View, Jl. Cemara Perum Cemara No. Ruko 1, Tlumpu, Sukorejo, Kota Blitar",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Vetma Pet and Poultry Shop Blitar"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Blitar",
                'nama_outlet' => "Cancha Pet Shop Blitar",
                'nama_pic' => 'PIC ' . "Cancha Pet Shop Blitar",
                'whatsapp' => "081249010752",
                'alamat_lengkap' => "Jl. Kelud Ruko Selatan Stadion No. 102C, Kepanjen Lor, Kepanjenkidul, Kota Blitar",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Cancha Pet Shop Blitar Blitar"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Blitar",
                'nama_outlet' => "Kinanti Petcare & Petshop",
                'nama_pic' => 'PIC ' . "Kinanti Petcare & Petshop",
                'whatsapp' => "089562226243",
                'alamat_lengkap' => "Jl. Buton No. 41, Kuningan, Kanigoro, Kabupaten Blitar",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Kinanti Petcare & Petshop Blitar"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Blitar",
                'nama_outlet' => "Sentra Petshop",
                'nama_pic' => 'PIC ' . "Sentra Petshop",
                'whatsapp' => "082142165528",
                'alamat_lengkap' => "Jl. Kalimantan No. 30, Sananwetan, Kota Blitar",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Sentra Petshop Blitar"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Malang",
                'nama_outlet' => "VDB Pet Shop",
                'nama_pic' => 'PIC ' . "VDB Pet Shop",
                'whatsapp' => "081228886000",
                'alamat_lengkap' => "Jl. Indragiri II No. 27, Purwantoro, Blimbing, Kota Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("VDB Pet Shop Malang"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Malang",
                'nama_outlet' => "House of Pet (HOP)",
                'nama_pic' => 'PIC ' . "House of Pet (HOP)",
                'whatsapp' => "03414371400",
                'alamat_lengkap' => "Ruko Soekarno Hatta, Jl. Soekarno Hatta Kav. 22, Kota Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("House of Pet (HOP) Malang"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Malang",
                'nama_outlet' => "Golden Pet Shop",
                'nama_pic' => 'PIC ' . "Golden Pet Shop",
                'whatsapp' => "0341335678",
                'alamat_lengkap' => "Jl. Buring No. 11, Oro-oro Dowo, Klojen, Kota Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Golden Pet Shop Malang"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Malang",
                'nama_outlet' => "Kimmy Pet Shop",
                'nama_pic' => 'PIC ' . "Kimmy Pet Shop",
                'whatsapp' => "085725900450",
                'alamat_lengkap' => "Jl. Kaliurang No. 68, Lowokwaru, Kota Malang",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Kimmy Pet Shop Malang"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Depok",
                'nama_outlet' => "Petshop Hemat Depok",
                'nama_pic' => 'PIC ' . "Petshop Hemat Depok",
                'whatsapp' => "081245699955",
                'alamat_lengkap' => "Jl. Raya Sawangan Depok No.26/27, Rangkapan Jaya, Kec. Pancoran Mas, Kota Depok",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Petshop Hemat Depok Depok"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Depok",
                'nama_outlet' => "JG Petshop",
                'nama_pic' => 'PIC ' . "JG Petshop",
                'whatsapp' => "02127612598",
                'alamat_lengkap' => "Jl. Raya Abdul Gani No.73, Jatimulya, Kec. Cilodong, Kota Depok",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("JG Petshop Depok"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Depok",
                'nama_outlet' => "Juanda Petshop",
                'nama_pic' => 'PIC ' . "Juanda Petshop",
                'whatsapp' => "081219486598",
                'alamat_lengkap' => "Jl. Ir H. Juanda No.20, Kemiri Muka, Kec. Beji, Kota Depok",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Juanda Petshop Depok"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Surabaya",
                'nama_outlet' => "Kawan Setia Petshop",
                'nama_pic' => 'PIC ' . "Kawan Setia Petshop",
                'whatsapp' => "081234567891",
                'alamat_lengkap' => "Jl. Raya Ngagel Jaya No. 14, Pucang Sewu, Kec. Gubeng, Kota Surabaya",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Kawan Setia Petshop Surabaya"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Surabaya",
                'nama_outlet' => "Raja Petshop",
                'nama_pic' => 'PIC ' . "Raja Petshop",
                'whatsapp' => "081234567892",
                'alamat_lengkap' => "Jl. Raya Kupang Indah No. 17, Dukuh Pakis, Kota Surabaya",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Raja Petshop Surabaya"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ],
            [
                'is_mitra' => false,
                'city_name' => "Surabaya",
                'nama_outlet' => "Surabaya Pet Care",
                'nama_pic' => 'PIC ' . "Surabaya Pet Care",
                'whatsapp' => "081234567893",
                'alamat_lengkap' => "Jl. Kenjeran No. 120, Kenjeran, Kota Surabaya",
                'latitude' => null,
                'longitude' => null,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=' . urlencode("Surabaya Pet Care Surabaya"),
                'featured' => false,
                'delivery_mode' => 'SELF_DELIVERY'
            ]
        ];

        // Central distributor fallback
        $centralDistributor = Distributor::where('nama', 'BentoCat Indonesia')->first() ?: Distributor::first();

        foreach ($outletsData as $data) {
            $city = City::where('nama', $data['city_name'])->first();
            if (!$city) {
                continue;
            }

            // Find distributor for this city or use fallback
            $distributor = Distributor::whereHas('city', function ($q) use ($data) {
                $q->where('nama', $data['city_name']);
            })->first();

            if (!$distributor) {
                $distributor = $centralDistributor;
            }

            if ($distributor) {
                Outlet::create([
                    'distributor_id' => $distributor->id,
                    'kota_id' => $city->id,
                    'nama_outlet' => $data['nama_outlet'],
                    'nama_pic' => $data['nama_pic'],
                    'whatsapp' => $data['whatsapp'],
                    'alamat_lengkap' => $data['alamat_lengkap'],
                    'latitude' => $data['latitude'],
                    'longitude' => $data['longitude'],
                    'google_maps_url' => $data['google_maps_url'],
                    'featured' => $data['featured'],
                    'is_mitra' => $data['is_mitra'],
                    'is_hidden' => !$data['is_mitra'], // Petshop Non Mitra Semuanya Disembunyikan
                    'status' => 'AKTIF',
                    'delivery_mode' => $data['delivery_mode']
                ]);
            }
        }
    }
}
